sudo: false
language: node_js
node_js:
  - 12 
cache: npm
branches:
  only:
    - dev
script:
  - hexo generate # generate static files
deploy:
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  provider: pages
  on:
    branch: master
  local-dir: public