# Site settings
entitle: Shell Cottage
cntitle: 贝壳小屋
email: haoxuan.wang14@student.xjtlu.edu.cn
description: A shelter for a lazy and terrible programmer, loving photograph and travelling!
baseurl: ""
url: "http://shellcottage.me"


author:
  name     : 'Horace Wang'
  cnname   : '王昊轩'
  email    : haoxuan.wang14@student.xjtlu.edu.cn
  url      : http://shellcottage.me/about/aboutMe.html
  facebook : https://www.facebook.com/weasley.bill.9
  enable_twitter: true
  twitter  : http://weibo.com/1602545844
  weibo    : http://weibo.com/1602545844
  zhihu    : https://www.zhihu.com/people/wang-hao-xuan-26
  github   : https://github.com/billweasley



comments: true
enable_disqus: true             #need to rebuild if you change this setting (run jekyll build)
disqus_shortname: 'shellcottage'
enable_duosuo: false             #need to rebuild if you change this setting
duoshuo_shortname: 'shellcottage'
google_analytics: UA-79915174-1

gems: [jekyll-paginate]
paginate: 4
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
highlighter: rouge
