# Site settings
entitle: Shell Cottage
cntitle: 贝壳小屋
email: haoxuan.wang14@student.xjtlu.edu.cn
description: A shelter for a lazy and terrible programmer, loving photograph and travelling!
baseurl: ""
url: "http://shellcottage.me"


author:
  name     : 'Horace Wang'
  cnname   : '王昊轩'
  introductive_url      : http://shellcottage.me/about/aboutMe.html
  enable_email: true
  email    : haoxuan.wang14@student.xjtlu.edu.cn
  enable_facebook: true
  facebook : https://www.facebook.com/weasley.bill.9
  enable_twitter: false
  twitter  :
  enable_weibo: true
  weibo    : http://weibo.com/1602545844
  enable_zhihu: true
  zhihu    : https://www.zhihu.com/people/wang-hao-xuan-26
  enable_github: true
  github   : https://github.com/billweasley
  enable_wechat : true
  url_wechatOR : http://shellcottage.me/about/myWeChat.jpeg


comments: true
enable_disqus: true             #need to rebuild if you change this setting (run jekyll build)
disqus_shortname: 'shellcottage'
enable_duosuo: true             #need to rebuild if you change this setting
duoshuo_shortname: 'shellcottage'
google_analytics: UA-79915174-1

gems: [jekyll-paginate]
paginate: 4
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
highlighter: rouge
